config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#            worked_periods GET    /worked_periods(.:format)                                                                worked_periods#index
#                           POST   /worked_periods(.:format)                                                                worked_periods#create
#         new_worked_period GET    /worked_periods/new(.:format)                                                            worked_periods#new
#        edit_worked_period GET    /worked_periods/:id/edit(.:format)                                                       worked_periods#edit
#             worked_period GET    /worked_periods/:id(.:format)                                                            worked_periods#show
#                           PATCH  /worked_periods/:id(.:format)                                                            worked_periods#update
#                           PUT    /worked_periods/:id(.:format)                                                            worked_periods#update
#                           DELETE /worked_periods/:id(.:format)                                                            worked_periods#destroy
#             welcome_index GET    /welcome/index(.:format)                                                                 welcome#index
#                      root GET    /                                                                                        welcome#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :worked_periods
  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

#:nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/worked_period.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: worked_periods
#
#  id         :bigint(8)        not null, primary key
#  ended_at   :datetime
#  started_at :datetime         not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

#
# Time spent working.
#
# @author [laura]
class WorkedPeriod < ApplicationRecord
  validates :started_at, presence: true
  validates :ended_at, presence: false
  validate :instance_validations

  include Timer

  scope :exclude, ->(record) { where.not(id: record.id) }

  scope :on, ->(date) { where('started_at': date.all_day) }

  scope :started_before_or_on, lambda { |moment|
    where('started_at <= :moment', moment: moment)
  }

  scope :started_after_or_on, lambda { |moment|
    where('started_at >= :moment', moment: moment)
  }

  scope :started_in_open_range, lambda { |inclusive_start, inclusive_end|
    started_before_or_on(
      inclusive_end
    ).started_after_or_on(
      inclusive_start
    )
  }

  scope :today, -> { on(Date.current) }

  scope :active, -> { where(ended_at: nil) }

  def self.active_period
    find_by(ended_at: nil)
  end

  def self.active_period?
    active_period.present?
  end

  def self.oldest
    WorkedPeriod.order(started_at: :asc).first
  end

  def self.youngest
    WorkedPeriod.order(started_at: :desc).first
  end

  def date
    started_at.to_date
  end

  def instance_validations
    validates_with WorkedPeriodValidator, DisjointTimersValidator
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/worked_periods_controller.rb
# frozen_string_literal: true

#:nodoc:
class WorkedPeriodsController < ApplicationController
  before_action :set_worked_period, only: %i[show edit update destroy]

  # GET /worked_periods
  # GET /worked_periods.json
  def index
    started_on = params.fetch(:started_on, WorkedPeriod.oldest.date)
    started_on = started_on.to_date.beginning_of_day

    ended_on = params.fetch(:ended_on, WorkedPeriod.youngest.date)
    ended_on = ended_on.to_date.end_of_day

    @worked_periods = WorkedPeriod.started_in_open_range(
      started_on, ended_on
    ).order(
      started_at: :asc
    )
    @worked_time = @worked_periods.to_a.sum(&:duration)
  end

  # GET /worked_periods/1
  # GET /worked_periods/1.json
  def show; end

  # GET /worked_periods/new
  def new
    @worked_period = WorkedPeriod.new
  end

  # GET /worked_periods/1/edit
  def edit; end

  # POST /worked_periods
  # POST /worked_periods.json
  def create
    @worked_period = WorkedPeriod.new(worked_period_params)

    respond_to do |format|
      if @worked_period.save
        format.html do
          redirect_to(
            @worked_period, notice: 'Time worked was successfully created.'
          )
        end
        format.json { render :show, status: :created, location: @worked_period }
      else
        format.html { render :new }
        format.json do
          render(json: @worked_period.errors, status: :unprocessable_entity)
        end
      end
    end
  end

  # PATCH/PUT /worked_periods/1
  # PATCH/PUT /worked_periods/1.json
  def update
    respond_to do |format|
      if @worked_period.update(worked_period_params)
        format.html do
          redirect_to(
            @worked_period, notice: 'Time worked was successfully updated.'
          )
        end
        format.json { render :show, status: :ok, location: @worked_period }
      else
        format.html { render :edit }
        format.json do
          render json: @worked_period.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /worked_periods/1
  # DELETE /worked_periods/1.json
  def destroy
    @worked_period.destroy
    respond_to do |format|
      format.html do
        redirect_to(
          worked_periods_url, notice: 'Time worked was successfully destroyed.'
        )
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_worked_period
    @worked_period = WorkedPeriod.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list.
  def worked_period_params
    params.require(:worked_period).permit(:started_at, :ended_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/worked_periods_helper.rb
module WorkedPeriodsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang-"en">
  <head>
    <!-- Meta tags required for bootstrap -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Demo</title>
    <!-- preven cross-site request forgery -->
    <%= csrf_meta_tags %>

    <!-- cache a nonce and reuse as long as the session lives, I think: https://bauland42.com/ruby-on-rails-content-security-policy-csp/ -->
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= link_to "Worked Periods", worked_periods_path %>

app/views/worked_periods/_form.html.erb
<%= form_with(model: worked_period, local: true) do |form| %>
  <% if worked_period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worked_period.errors.count, "error") %> prohibited this worked_period from being saved:</h2>

      <ul>
      <% worked_period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= form.label :ended_at %>
    <%= form.datetime_select :ended_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worked_periods/edit.html.erb
<h1>Editing Time Worked</h1>

<%= render 'form', worked_period: @worked_period %>

<%= link_to 'Show', @worked_period %> |
<%= link_to 'Back', worked_periods_path %>

app/views/worked_periods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worked Periods</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @worked_periods.each do |worked_period| %>
      <tr>
        <td><%= worked_period.date %></td>
        <td><%= worked_period.started_at.to_s(:time) %></td>
        <td><%= worked_period.ended_at ? worked_period.ended_at.to_s(:time) : '' %></td>
        <td><%= distance_of_time_in_words(worked_period.duration) %></td>
        <td>(<%= Time.at(worked_period.duration).utc.strftime("%H:%M:%S") %>)</td>
        <td><%= link_to 'Show', worked_period %></td>
        <td><%= link_to 'Edit', edit_worked_period_path(worked_period) %></td>
        <td><%= link_to 'Destroy', worked_period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td>Total</td>
      <td></td>
      <td></td>
      <td><%= distance_of_time_in_words(@worked_periods.to_a.sum(&:duration)) %></td>
      <td>(<%= (@worked_periods.to_a.sum(&:duration).seconds/3600).to_i.to_s.rjust(2,'0') + ":"+Time.at(@worked_periods.to_a.sum(&:duration)).utc.strftime("%M:%S") %>)</td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Time Worked', new_worked_period_path %>

app/views/worked_periods/new.html.erb
<h1>New Time Worked</h1>

<%= render 'form', worked_period: @worked_period %>

<%= link_to 'Back', worked_periods_path %>

app/views/worked_periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @worked_period.started_at %>
</p>

<p>
  <strong>End:</strong>
  <%= @worked_period.ended_at %>
</p>

<%= link_to 'Edit', edit_worked_period_path(@worked_period) %> |
<%= link_to 'Back', worked_periods_path %>